name: Build Android APK
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      # यह कमांड मिसिंग एंड्रॉइड फ़ोल्डर और build.gradle फ़ाइलों को दोबारा बना देगा
      - name: Repair Android Project Files
        run: flutter create --platforms=android .

      - name: Get Dependencies
        run: flutter pub get

      - name: Clean Project
        run: flutter clean

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: student-sathi-apk
          path: build/app/outputs/flutter-apk/app-release.apk
